jQuery.sap.registerPreloadedModules({
	"version": "2.0",
	"name": "sap/ui/app/Component-preload",
	"modules": {
		"sap/ui/app/Component.js": "sap.ui.define([\"sap/ui/core/UIComponent\",\"sap/ui/model/json/JSONModel\",\"sap/ui/model/resource/ResourceModel\"],function(e,n,i){\"use strict\";return e.extend(\"sap.ui.app.Component\",{metadata:{manifest:\"json\"},init:function(){e.prototype.init.apply(this,arguments);var t={recipient:{name:\"Peter\"}},o=new n(t),s=new i({bundleName:\"sap.ui.app.i18n.i18n\"});this.setModel(o),this.setModel(s,\"i18n\")}})});",
		"sap/ui/app/controller/App.controller.js": "sap.ui.define([\"sap/ui/core/mvc/Controller\",\"sap/m/MessageToast\"],function(e,s){\"use strict\";return e.extend(\"sap.ui.app.controller.App\",{})});",
		"sap/ui/app/controller/HelloPanel.controller.js": "sap.ui.define([\"sap/ui/core/mvc/Controller\",\"sap/m/MessageToast\"],function(e,o){\"use strict\";return e.extend(\"sap.ui.app.controller.HelloPanel\",{onShowHello:function(){var e=this.getView().getModel(\"i18n\").getResourceBundle(),t=this.getView().getModel().getProperty(\"/recipient/name\"),i=e.getText(\"helloMsg\",[t]);o.show(i)},_getDialog:function(){return this._oDialog||(this._oDialog=sap.ui.xmlfragment(\"sap.ui.app.view.fragment.HelloDialog\",this),this.getView().addDependent(this._oDialog)),this._oDialog},onOpenDialog:function(){this._getDialog().open()},onCloseDialog:function(){this._getDialog().close()}})});",
		"sap/ui/app/view/fragment/HelloDialog.fragment.xml": "<core:FragmentDefinition\n  xmlns=\"sap.m\"\n  xmlns:core=\"sap.ui.core\"><Dialog\n    title=\"Hello {/recipient/name}\"><content><core:Icon\n        src=\"sap-icon://hello-world\"\n        size=\"5rem\"\n        class=\"sapUiSmallMargin\"/></content><beginButton><Button\n        text=\"{i18n>dialogCloseButtonText}\"\n        press=\"onCloseDialog\"/></beginButton></Dialog></core:FragmentDefinition>\n",
		"sap/ui/app/view/App.view.xml": "<mvc:View\n  controllerName=\"sap.ui.app.controller.App\"\n  xmlns=\"sap.m\"\n  xmlns:mvc=\"sap.ui.core.mvc\"\n  displayBlock=\"true\"><App><pages><Page title=\"{i18n>homePageTitle}\"><content><mvc:XMLView viewName=\"sap.ui.app.view.HelloPanel\"/></content></Page></pages></App></mvc:View>\n",
		"sap/ui/app/view/HelloPanel.view.xml": "<mvc:View\n  controllerName=\"sap.ui.app.controller.HelloPanel\"\n  xmlns=\"sap.m\"\n  xmlns:mvc=\"sap.ui.core.mvc\"><Panel\n    headerText=\"Hello {/recipient/name}\"\n    class=\"sapUiResponsiveMargin\"\n    width=\"auto\"><content><Input\n        value=\"{/recipient/name}\"\n        valueLiveUpdate=\"true\"\n        width=\"60%\"/><Button\n        text=\"{i18n>showHellowButtonText}\"\n        press=\"onShowHello\"\n        class=\"sapUiSmallMarginEnd\"/><Button\n        icon=\"sap-icon://world\"\n        text=\"{i18n>openDialogButtonText}\"\n        press=\"onOpenDialog\"/></content></Panel></mvc:View>\n",
		"sap/ui/app/i18n/i18n_en_US.properties": "# Fallback file\n# App Descriptor\nappTitle=OpenUI5 Boilerplate\nappDescription=Boilerplate for OpenUI5/SAPUI5\n\n# Hello Panel\nshowHellowButtonText=Say Hello\nhelloMsg=Hello {0}\nhomePageTitle=OpenUI5 Boilerplate\nopenDialogButtonText=Say Hello With Dialog\ndialogCloseButtonText=Ok\n"
	}
});